# TOY: not secure (small parameters, non-constant-time, naive hash-to-group)
"""Uniform prime-order group interface used by the DLP solvers and protocol toys.

Two instantiations:

* ``ModPGroup``  -- the order-q subgroup of quadratic residues in Z_p^*,
  p = 2q + 1 a safe prime.
* ``ECGroup``    -- the subgroup generated by a point G of prime order n on an
  ``EllipticCurve``.

Both expose: ``identity``, ``generator``, ``order``, ``op(a, b)``,
``exp(a, k)``, ``inv(a)``, ``eq(a, b)``, ``random_scalar(rng)``,
``hash_to_group(data)``, ``encode(a) -> bytes``.
"""
from __future__ import annotations

import hashlib
import random

from sympy import isprime, nextprime

from .curve import EllipticCurve, find_prime_order_curve

# Safe primes p = 2q + 1 (found by search from 2^(k-2); used as toy defaults).
SAFE_PRIME_64 = 9223372036854778487
SAFE_PRIME_128 = 170141183460469231731687303715884114527


def safe_prime(bits: int, start: int | None = None) -> int:
    """Smallest safe prime p = 2q + 1 with q >= start (default 2^(bits-2))."""
    q = start if start is not None else (1 << (bits - 2)) + 1
    q = nextprime(q - 1)
    while not isprime(2 * q + 1):
        q = nextprime(q)
    return 2 * q + 1


class ModPGroup:
    """Quadratic-residue subgroup of Z_p^* (prime order q = (p-1)/2)."""

    def __init__(self, p: int = SAFE_PRIME_64, g: int = 4):
        if not (isprime(p) and isprime((p - 1) // 2)):
            raise ValueError("p must be a safe prime")
        self.p, self.q = p, (p - 1) // 2
        self.g = g % p
        if pow(self.g, self.q, p) != 1 or self.g in (0, 1):
            raise ValueError("g must generate the QR subgroup")
        self.identity = 1
        self.generator = self.g
        self.order = self.q

    def __repr__(self):
        return f"ModPGroup(p={self.p}, q={self.q}, g={self.g})"

    def op(self, a, b):
        return a * b % self.p

    def exp(self, a, k: int):
        return pow(a, k % self.q, self.p)

    def inv(self, a):
        return pow(a, -1, self.p)

    def eq(self, a, b) -> bool:
        return a % self.p == b % self.p

    def contains(self, a) -> bool:
        return 0 < a < self.p and pow(a, self.q, self.p) == 1

    def random_scalar(self, rng=None) -> int:
        rng = rng or random.SystemRandom()
        return rng.randrange(1, self.q)

    def hash_to_group(self, data: bytes) -> int:
        """Square of a hash value mod p (lands in the QR subgroup; log unknown)."""
        ctr = 0
        while True:
            h = int.from_bytes(hashlib.sha256(b"H2G" + ctr.to_bytes(4, "big") + data).digest() * 2, "big") % self.p
            if h > 1:
                return h * h % self.p
            ctr += 1

    def encode(self, a) -> bytes:
        return int(a).to_bytes((self.p.bit_length() + 7) // 8, "big")

    def key(self, a):
        return a

    @classmethod
    def small(cls, bits: int = 32):
        """A fresh small safe-prime group (for DLP attack experiments)."""
        return cls(safe_prime(bits), 4)


class ZpStarGroup:
    """The full multiplicative group Z_p^* (order p - 1, composite) -- for
    Pohlig–Hellman experiments with smooth p - 1."""

    def __init__(self, p: int, g: int):
        if not isprime(p):
            raise ValueError("p must be prime")
        self.p, self.g = p, g % p
        self.identity, self.generator, self.order = 1, self.g, p - 1

    def op(self, a, b):
        return a * b % self.p

    def exp(self, a, k: int):
        return pow(a, k % (self.p - 1), self.p)

    def inv(self, a):
        return pow(a, -1, self.p)

    def eq(self, a, b) -> bool:
        return a % self.p == b % self.p

    def key(self, a):
        return a

    def random_scalar(self, rng=None) -> int:
        rng = rng or random.SystemRandom()
        return rng.randrange(1, self.p - 1)


class ECGroup:
    """Cyclic subgroup <G> of prime order n on an elliptic curve (additive written as op)."""

    def __init__(self, curve: EllipticCurve, G, n: int, cofactor: int | None = None):
        self.E, self.G, self.n = curve, G, n
        self.cofactor = cofactor   # None: computed by naive counting (small p) or assumed 1
        self.identity = None
        self.generator = G
        self.order = n

    def __repr__(self):
        return f"ECGroup({self.E}, n={self.n})"

    def op(self, P, Q):
        return self.E.add(P, Q)

    def exp(self, P, k: int):
        return self.E.jmul(k % self.n, P)

    def inv(self, P):
        return self.E.neg(P)

    def eq(self, P, Q) -> bool:
        return P == Q

    def contains(self, P) -> bool:
        return self.E.is_on_curve(P) and self.E.mul(self.n, P) is None

    def random_scalar(self, rng=None) -> int:
        rng = rng or random.SystemRandom()
        return rng.randrange(1, self.n)

    def hash_to_group(self, data: bytes):
        """Try-and-increment to a curve point, then clear cofactor."""
        p = self.E.p
        ctr = 0
        cof = None
        while True:
            x = int.from_bytes(hashlib.sha256(b"H2C" + ctr.to_bytes(4, "big") + data).digest() * 2, "big") % p
            P = self.E.lift_x(x)
            ctr += 1
            if P is None:
                continue
            if cof is None:
                cof = self.cofactor
                if cof is None:
                    cof = self.E.order() // self.n if p <= 10 ** 7 else 1
            Q = self.E.mul(cof, P)
            if Q is not None:
                return Q

    def encode(self, P) -> bytes:
        if P is None:
            return b"\x00"
        L = (self.E.p.bit_length() + 7) // 8
        return b"\x04" + P[0].to_bytes(L, "big") + P[1].to_bytes(L, "big")

    def key(self, P):
        return P

    @classmethod
    def small(cls, p: int = 10007, seed: int = 0):
        """Prime-order toy curve over GF(p) (found by search)."""
        E, G = find_prime_order_curve(p, seed)
        return cls(E, G, E.order())
